from .auxiliares import mostrar_el_menu, obtener_total_vehiculos
from .validaciones import validar_numero
from .funciones_principales import mostrar_existencias, calcular_total_vehiculos, calcular_garage_menos_unidades, calcular_mayor_cant_unidades, \
calcular_recaudacion_total, cantidad_garages_seis_o_mas, mostrar_porcentajes_y_garage_mas_importante